# Generated by Django 3.0.2 on 2020-01-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('doctor_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('vacant', models.BooleanField(default=True)),
                ('patient_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
