# Generated by Django 3.0.2 on 2020-01-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('specialization', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('vacant', models.BooleanField(default=True)),
                ('patient_name', models.CharField(blank=True, max_length=20)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Doctor')),
            ],
        ),
    ]
