# Generated by Django 3.0.2 on 2020-01-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor_name',
            field=models.CharField(max_length=20),
        ),
    ]
