# Generated by Django 3.0.2 on 2020-01-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200126_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
